# recipe/meta.yaml
package:
  name: quantms-rescoring
  version: "0.0.5"

source:
  path: ../

build:
  entry_points:
    - rescoring=quantmsrescore.rescoring:main
  run_exports:
    - {{ pin_subpackage('quantms-rescoring', max_pin="x.x") }}
  script: "{{ PYTHON }} -m pip install . --no-deps --no-build-isolation --no-cache-dir -vvv"
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.9,<3.12
    - pip
    - poetry-core >=1.2.0
  run:
    - python >=3.9,<3.12
    - click
    - pyopenms>=2.4.0
    - pandas
    - numpy>=1.25
    - ms2rescore=3.1.4
    - deepLC>=3.0
    - psm-utils
    - scipy
    - pygam
    - protobuf
    - ms2pip>=4.0
test:
  imports:
    - quantmsrescore
  commands:
    - rescoring --help

about:
  home: https://www.github.com/bigbio/quantms-rescoring
  summary: PSM rescoring python package with scripts and helpers for the quantms workflow
  license: Apache 2.0
  license_file: LICENSE
  dev_url: https://www.github.com/bigbio/quantms-rescoring

extra:
  recipe-maintainers:
    - ypriverol
