engines:
  eslint:
    enabled: true
  pylint:
    enabled: true
  remark-lint:
    enabled: true
    rules:
      html:
        allowed_elements:
          - details
          - summary

eslint:
  config_file: .eslintrc.json

exclude_paths:
  - 'tests/**'
exclude_paths:
    - 'tests/**'